polls-master/macro_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('',include('polls.urls')),
    path('',views.home_view,name='home'),
    path('accounts/', include('allauth.urls')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

handler404 = 'macro_project.views.no_page_found'

polls-master/polls/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    path('allpolls/', views.polls_view, name='allpolls'),
    path('allpolls/<str:id>/', views.poll_view, name='poll'),
    path('submitpoll/', views.submit_poll_view, name='submit_poll'),
    path('getpolldata/',views.get_poll_data,name='getpolls'),
    path('toppolls/',views.top_polls,name='toppolls'),
    path('comment/', views.comment_view, name='comment'),
    path('searchpoll/',views.search_view,name='search'),
]

handler404 = 'macro_project.views.no_page_found'

polls-master/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'users'
urlpatterns=[
    path('register/',views.register_view,name='register'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('profile/',views.profile_view,name='profile')
]

handler404 = 'macro_project.views.no_page_found'

polls-master/templates/P404.html
{% extends 'base.html' %}

{% block content %}
<div class="container m-5 p-5">
    <div class="jumbotron">
        <h1 class="display-4">404 ERROR</h1>
        <p class="lead">The link you followed may be broken, or the page may have been removed. Go back to PollPoller..</p>
        <hr class="my-4">
        <p>The link you followed may be broken, or the page may have been removed. Go back to PollPoller.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'polls:allpolls' %}" role="button">Go to website</a>
        </p>
    </div>
</div>
{% endblock %}

polls-master/templates/base.html
{% load static  %}
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        
    </head>

    <body>

        <!-- Image and text -->
        <nav class="navbar navbar-dark sticky-top " style="background-color: #111;">
            <a class="navbar-brand h1 mt-3 " href="{% url 'polls:allpolls' %}">
                <h2>PollPoller</h2>
            </a>
            
            {% if user.is_authenticated %}
                <div class="d-flex">
                    <div class="mr-3 pt-1">
                        <div class="">
                            <input class="form-control  search-polls" type="search" placeholder="Search a Poll"
                                aria-label="Search">
                            <ul class="list-group suggestions-box border border-dark">
                                
                            </ul>
                        </div>
                    </div>
                    <div class="logged-in-nav ">
                        <h2 class="text-white mr-3">Hello  <a href="{% url 'users:profile' %}" style="color: white;text-decoration: none;">{{user.username}}</a> </h2>
                        <a href="{% url 'users:logout' %}"><button class="btn btn-light">
                                <h5>Logout</h5>
                            </button></a>
                    </div>
                </div>
                
            {% endif %}
            
        </nav>
        <div class="mb-4" >
            {% block content %}
            {% endblock %}
        </div>
        
        <script>
            $(document).ready(function (){

                $('.search-polls').on('input',(e)=>{
                    $.ajax({
                        type : 'GET',
                        url : '/searchpoll/',
                        data : {
                            'name' : e.target.value
                        }
                    }).done((res)=>{
                        console.log(res.data)
                        if(res.data === []){
                            
                            $('.suggestions-box').empty()
                            return ;
                        }
                        $('.suggestions-box').empty()
                        res.data.forEach( item =>{
                            console.log(item)
                            let li = document.createElement('a')
                            li.setAttribute('href','/allpolls/'+item[1])
                            li.className='list-group-item-action bg-white text-dark p-2'
                            li.innerHTML = item[0]
                            $('.suggestions-box').append(li)
                        })
                    })
                })

            });
        </script>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </body>

</html>

polls-master/templates/home.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>

<body>

    <!-- Image and text -->
    <div class="back-ground">
        <div>
            <img class='back-ground-image' src="{% static 'images/bg.jpg' %}" alt="">
        </div>
        
    <nav class="navbar navbar-dark" style="background-color: #111;">
        <a class="navbar-brand h1" href="#">
            <h2>PollPoller</h2>
        </a>
    </nav>
       <a href="{% url 'users:register' %}" class="text-white" style="text-decoration: none;">
            <button class="btn btn-dark p-2 h5">Get Started</button>
        </a>
       <div class="matter">
            <p class="text-white h5">
            
            This website allows you to post some polls on different aspects by different individuals.
            
            Gearing up to the opinions of every individual, you will have a few questions in which every participant can poll
            according to their views.
            
            Each answer should be selected from the given set of options.
            
            Every option you choose, will be your opinion for that particular question.
            
            Extending to this, you can also comment on the imposed question when you are not satisfied with the given set of
            options.
            
            Hope you will find this interesting.
            
            There we go!!

                
            </p>
       </div>
        
    </div>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</body>