polls-master/macro_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('',include('polls.urls')),
    path('',views.home_view,name='home'),
    path('accounts/', include('allauth.urls')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

handler404 = 'macro_project.views.no_page_found'

polls-master/polls/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    path('allpolls/', views.polls_view, name='allpolls'),
    path('allpolls/<str:id>/', views.poll_view, name='poll'),
    path('submitpoll/', views.submit_poll_view, name='submit_poll'),
    path('getpolldata/',views.get_poll_data,name='getpolls'),
    path('toppolls/',views.top_polls,name='toppolls'),
    path('comment/', views.comment_view, name='comment'),
    path('searchpoll/',views.search_view,name='search'),
]

handler404 = 'macro_project.views.no_page_found'

polls-master/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'users'
urlpatterns=[
    path('register/',views.register_view,name='register'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('profile/',views.profile_view,name='profile')
]

handler404 = 'macro_project.views.no_page_found'

polls-master/polls/models.py
from django.db import models
from datetime import datetime
# Create your models here.
from django.contrib.auth.models import User
from django.utils import timezone


class Poll(models.Model):
    title = models.CharField(max_length=50)
    date = models.DateTimeField(default=datetime.now)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class PollsOptions(models.Model):
    pollOption = models.CharField(max_length=30)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    pollOptionVotes = models.IntegerField(default=0)

    def __str__(self) :
        return self.poll.title + ' ' +self.pollOption

class CommentBy(models.Model):
    poll = models.ForeignKey(Poll,on_delete=models.CASCADE)
    comment = models.TextField(null=True)
    comment_by = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now)

class VotedBy(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    polled_by = models.ForeignKey(User,on_delete=models.CASCADE)
    polledOpt = models.ForeignKey(PollsOptions,on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now)

polls-master/users/models.py
from django.db import models

# Create your models here.

polls-master/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.db import models
from django.forms import fields, widgets

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists")

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username','password']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']

polls-master/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .forms import ProfileForm, RegisterForm,LoginForm
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from polls.models import *
# Create your views here.
def register_view(request):
    if request.user.is_authenticated:
        return redirect('polls:allpolls')
    else:
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            
            if form.is_valid():
                user = form.save(commit=False)

                email = request.POST.get('email')
                user.email = email
                user.save()
                send_mail(
                    'From PollPoller',
                    'Poll Poller welcomes you ',
                    'abhinaisai10@gmail.com',
                    [email],
                    fail_silently=True
                )
                username = form.cleaned_data.get('username')
                messages.success(request,f"Account created for {username}")
                return redirect('users:login')
        else:
            form = RegisterForm()
        context = {
            'form' : form
        }
    return render(request,'users/register.html',context)

def login_view(request):
    if request.user.is_authenticated:
        return redirect('polls:allpolls')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request,username=username,password=password)
            if user is not None:
                login(request,user)
                return redirect('polls:allpolls')
            else:
                form = LoginForm(data=request.POST)
                return render(request,'users/login.html',{'form':form})

        else:
            form  = LoginForm()
            context = {
                'form' : form
            }
    return render(request,'users/login.html',context)

def logout_view(request):
    logout(request)
    return redirect('users:login')


@login_required(login_url='users:login')
def profile_view(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
        else:
            userpolls = Poll.objects.filter(creator=request.user)
            polls = []
            for i in range(0, len(userpolls), 2):
                try:
                    polls.append([userpolls[i], userpolls[i+1]])
                except:
                    polls.append([userpolls[i]])
            context = {
                'form': form,
                'polls': polls,
            }
            return  render(request, 'users/profile.html',context)
    else:
        form = ProfileForm(instance=request.user)


    userpolls = Poll.objects.filter(creator = request.user)
    polls = []
    for i in range(0,len(userpolls),2):
        try:
            polls.append([userpolls[i],userpolls[i+1]])
        except:
            polls.append([userpolls[i]]) 
    context = {
        'form': form,
        'polls':polls,
    }

    return render(request, 'users/profile.html', context)

polls-master/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% load socialaccount %}
<div class="container mt-5 register-container ">
    <div class="register-image-container">
        <img class="register-image" src="{% static 'images/register.jpg' %}" alt="">
    </div>
    <div class="form-container ">
        <form action="" method="post">
            {% csrf_token %}
            <fieldset>
                <div class="bd bottom mb-3">
                    <h2>Login Into Your Account</h2>
                </div>
                <div>
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">{{message}}</div>
                    {% endfor %}
                    {% endif %}
                </div>
                <div>
                    {{form|crispy}}
                </div>
            </fieldset>
            <div class="form-bottom ">
                <p class="mr-2">
                    New User?
                    <a href="{% url 'users:register' %}">Sign Up</a>
                </p>
                <button class="btn btn-primary">Sign In</button>
            </div>
            <div class="d-flex justify-content-end mb-4">
                <a href="{% url 'password_reset' %}">Forgot password?</a>
            </div>
        </form>
        <a class="btn btn-danger text-center d-flex align-items-center justify-content-center text-center"
            href="{% provider_login_url 'google' %}">Sign in with Google</a>
    </div>
</div>

{% endblock %}

polls-master/templates/users/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container m-5 p-5">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

polls-master/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
<div class="alert alert-info">
    Your password has been set.
</div>
<a href="{% url 'users:login' %}">Sign In Here</a>
{% endblock content %}

polls-master/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Reset Password</button>
        </div>
    </form>
</div>
{% endblock content %}

polls-master/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block content %}
<div class="alert alert-info">
    An email has been sent with instructions to reset your password
</div>
{% endblock content %}

polls-master/templates/users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
        <div class="container border rounded border-dark p-4 mt-5 mb-4">
            <div class="container border-bottom border-dark h3">
                Update Your Details
            </div>
            <div class="container">
                <form action="" method="post">
                    {% csrf_token %}
                    {{form|crispy}}
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-dark">Update</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="container border rounded border-dark p-4">
            <div class="container border-bottom border-dark m-3">
                <p class="h5">Mypolls</p>
            </div>
            {% if polls|length %}
                <div class="container">
                    {% for poll in polls %}
                        <div class="row">
                            {% for each in poll %}
                            <div class="col">
                                
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title">
                                            <a href="{% url 'polls:poll' each.id %}">{{each.title}}</a>
                                        </h5>
                                        <h6 class="card-subtitle mb-2">
                                            Created on {{each.date|date:"F j, Y, g:i A"}}
                                        </h6>
                                        <div class="d-flex">
                                            <p class="mr-3">Votes : {{each.votedby_set.all|length}}</p>
                                            <p>Comments : {{ each.commentby_set.all|length }}</p>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                            {% endfor %}
                            
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="container">
                    No polls yet
                </div>
            {% endif %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}

polls-master/templates/users/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-5 register-container ">
        <div class="register-image-container">
            <img class="register-image" src="{% static 'images/register.jpg' %}" alt="">
        </div>
        <div class="form-container">
            <form action="" method="post">
                {% csrf_token %}
                <fieldset>
                    <div class="bd bottom mb-3">
                        <h2>Register Your Account</h2>
                    </div>
                    <div>
                        {% for field in form %}
                            {{field|as_crispy_field}}
                        {% endfor %}
                    </div>
                </fieldset>
                <div  class="form-bottom ">
                    <p class="mr-2">
                        Already have an account? 
                        <a href="{% url 'users:login' %}">Sign In</a> </p>
                    <button class="btn btn-primary">Sign Up</button>
                </div>
            </form>
        </div>
       
    </div>
{% endblock %}